export const siteConfig = {
  brand: {
    name: "Prime Heating & Cooling",
    shortName: "PRIME HEATING & COOLING",
    tagline: "Heating · Cooling · Indoor Comfort",
    city: "Your Service Area",
    state: "",
    phoneDisplay: "(555) 555-0100",
    phoneHref: "+15555550100",
    email: "service@primehvac.com",
  },
  hero: {
    eyebrow: "4.9★ rated local HVAC team",
    heading: "Comfort back. Without the runaround.",
    body: "Fast HVAC help. Clear answers. Careful work.",
    image: "/hvac/hero-tech.svg",
    imageAlt: "Smiling HVAC technician beside residential air conditioning equipment",
  },
  trust: [
    "Fast appointment options",
    "Licensed & insured",
    "Clear recommendations",
    "Quality workmanship",
  ],
  stats: [
    { value: "4.9★", label: "Homeowner rating" },
    { value: "Fast", label: "Appointment options" },
    { value: "Clear", label: "Options before work starts" },
    { value: "Local", label: "Neighborhood service" },
  ],
  services: [
    {
      key: "cooling",
      title: "AC Repair",
      copy: "No cold air, weak airflow, strange noises, or an AC that cannot keep up.",
      image: "/hvac/ac-repair.svg",
      imageAlt: "HVAC technician servicing a residential air conditioning system",
    },
    {
      key: "heating",
      title: "Heating & Furnace Repair",
      copy: "Find the problem, explain the options, and get dependable heat moving again.",
      image: "https://lirp.cdn-website.com/2d412503/dms3rep/multi/opt/MikeFurnace-1920w.jpg",
      imageAlt: "Technician inspecting and repairing a residential furnace",
    },
    {
      key: "air",
      title: "Indoor Air Quality",
      copy: "Cleaner air, better filtration, balanced humidity, and healthier indoor comfort.",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=84",
      imageAlt: "Indoor air quality and clean home comfort",
    },
    {
      key: "duct",
      title: "Ductwork & Airflow",
      copy: "Help for weak airflow, uneven rooms, damaged ducts, and wasted comfort.",
      image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=84",
      imageAlt: "HVAC technician inspecting ductwork and airflow",
    },
    {
      key: "thermostat",
      title: "Thermostats & Smart Controls",
      copy: "Setup, replacement, and control troubleshooting without the technical headache.",
      image: "https://images.unsplash.com/photo-1774876549476-254b00a5d648?auto=format&fit=crop&w=1200&q=84",
      imageAlt: "Technician helping a homeowner with a smart thermostat",
    },
    {
      key: "maintenance",
      title: "Maintenance & Tune-Ups",
      copy: "Seasonal checks that catch small problems before they become expensive breakdowns.",
      image: "https://camairhvac.com/pictures/team-photo.jpg",
      imageAlt: "HVAC technician performing maintenance on residential equipment",
    },
    {
      key: "installation",
      title: "System Replacement",
      copy: "Clear replacement choices, clean installation, startup, testing, and final walkthrough.",
      image: "https://images.unsplash.com/photo-1626178793926-22b28830aa30?auto=format&fit=crop&w=1200&q=84",
      imageAlt: "Residential HVAC replacement and installation",
    },
    {
      key: "emergency",
      title: "Emergency HVAC Service",
      copy: "Urgent heating and cooling help when comfort cannot wait until tomorrow.",
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=84",
      imageAlt: "Home service technician responding to an urgent HVAC repair",
    },
    {
      key: "commercial",
      title: "Light Commercial HVAC",
      copy: "Dependable heating and cooling service for offices, shops, and small businesses.",
      image: "https://images.unsplash.com/photo-1771902985060-6133bb4b2eb6?auto=format&fit=crop&w=1200&q=84",
      imageAlt: "Commercial rooftop HVAC technician and equipment",
    },
  ],
  reviews: [
    { quote: "They were on time, explained the problem in plain English, and had the AC running again before the house got miserable.", name: "Sarah M.", location: "Homeowner" },
    { quote: "I knew what the options were before any work started. No pressure, no confusing pitch.", name: "James R.", location: "Homeowner" },
    { quote: "Clean work, easy communication, and no surprises when the job was finished.", name: "Nicole T.", location: "Homeowner" },
    { quote: "The technician listened first, checked the system, then showed me exactly what was wrong.", name: "Robert K.", location: "Homeowner" },
    { quote: "Our AC quit in the afternoon. They found an opening quickly and got cold air moving again that day.", name: "Michael R.", location: "Homeowner" },
    { quote: "The replacement was organized from estimate through final walkthrough. Everything felt straightforward.", name: "David M.", location: "Homeowner" },
  ],
  projects: [
    {
      title: "Cooling system service",
      image: "/hvac/ac-repair.svg",
      imageAlt: "Technician working on residential air conditioning equipment",
      copy: "Hands-on diagnosis where cooling problems start, followed by a clear explanation of the fix.",
    },
    {
      title: "Heating diagnostics",
      image: "https://lirp.cdn-website.com/2d412503/dms3rep/multi/opt/MikeFurnace-1920w.jpg",
      imageAlt: "Technician inspecting a residential furnace",
      copy: "Heating troubleshooting at the equipment before repair or replacement decisions are made.",
    },
    {
      title: "Comfort controls",
      image: "https://images.unsplash.com/photo-1774876549476-254b00a5d648?auto=format&fit=crop&w=1200&q=84",
      imageAlt: "Home comfort controls and thermostat service",
      copy: "Simple control setup so the system is easier to understand and more comfortable to live with.",
    },
  ],
  local: {
    image: "/hvac/local-tech.svg",
    imageAlt: "Smiling local HVAC technician giving a thumbs up beside an outdoor air conditioning unit",
    badges: [
      "Local technicians",
      "Fast response",
      "Residential HVAC",
      "Repair & replacement",
      "Nearby neighborhoods",
      "Call to confirm your area",
    ],
  },
  faqs: [
    { question: "How quickly can I get service?", answer: "Availability changes by day and season. Call or request service online and we can confirm the earliest opening." },
    { question: "Should I repair or replace my HVAC system?", answer: "That depends on equipment age, repair cost, comfort, efficiency, and expected remaining life. We can inspect the system and explain both options." },
    { question: "How often should HVAC maintenance be scheduled?", answer: "Many homeowners schedule cooling service before summer and heating service before winter so small problems are found before peak season." },
    { question: "Do you service heat pumps?", answer: "Yes. Heat-pump diagnostics, repair, maintenance, and replacement can be handled as part of residential HVAC service." },
    { question: "Can I request service online?", answer: "Yes. Use Schedule Service or call directly and tell us what is happening." },
    { question: "Do you service my neighborhood?", answer: "We serve homeowners throughout the local area and nearby communities. Call to confirm your address and the earliest available appointment." },
  ],
  serviceAreas: [
    "Your neighborhood",
    "Nearby communities",
    "Fast local response",
    "Residential service",
    "Local technicians",
    "Call to confirm your area",
  ],
} as const
