export const siteConfig = {
  brand: {
    name: "Prime Heating & Cooling",
    shortName: "PRIME HEATING & COOLING",
    tagline: "Heating · Cooling · Indoor Comfort",
    city: "Your Service Area",
    state: "",
    phoneDisplay: "(555) 555-0100",
    phoneHref: "+15555550100",
    email: "service@primehvac.com",
  },
  hero: {
    eyebrow: "Trusted local heating & cooling service",
    heading: "Fast, reliable heating & cooling service.",
    body: "Repair, replacement, maintenance, and indoor comfort help from technicians who show up ready to solve the problem.",
    image: "https://images.unsplash.com/photo-1621905252472-e0b72f995afc?auto=format&fit=crop&w=1800&q=90",
  },
  trust: [
    "Same-day appointments",
    "Licensed & insured",
    "Clear recommendations",
    "Residential HVAC specialists",
  ],
  stats: [
    { value: "4.9", label: "Google rating" },
    { value: "15+", label: "Years serving homeowners" },
    { value: "5,000+", label: "Service calls completed" },
    { value: "24/7", label: "Emergency availability" },
  ],
  services: [
    { key: "cooling", title: "Air Conditioning Repair", copy: "Fast diagnostics and dependable AC repairs when your home stops cooling properly.", image: "https://images.unsplash.com/photo-1631545806609-94b8478bbd8b?auto=format&fit=crop&w=1200&q=85" },
    { key: "installation", title: "AC Installation", copy: "Right-sized cooling systems installed cleanly for dependable summer comfort.", image: "https://images.unsplash.com/photo-1626178793926-22b28830aa30?auto=format&fit=crop&w=1200&q=85" },
    { key: "heating", title: "Heating Repair", copy: "Furnace and heat-pump repairs that get warm air moving again without unnecessary delay.", image: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1200&q=85" },
    { key: "installation", title: "Heating Installation", copy: "Replacement options explained clearly, then installed and tested the right way.", image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=85" },
    { key: "maintenance", title: "HVAC Maintenance", copy: "Seasonal tune-ups that help prevent surprise breakdowns and protect performance.", image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=85" },
    { key: "air", title: "Indoor Air Quality", copy: "Filtration, airflow, humidity, and air-quality solutions for a healthier-feeling home.", image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=85" },
    { key: "duct", title: "Ductwork & Airflow", copy: "Airflow problems, duct repairs, and comfort balancing for rooms that never feel right.", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=85" },
    { key: "emergency", title: "Emergency HVAC Service", copy: "Urgent heating and cooling support when comfort problems cannot wait until tomorrow.", image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=85" },
    { key: "thermostat", title: "Thermostats & Controls", copy: "Smart thermostats, controls, and setup help so the system is easier to live with.", image: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=85" },
    { key: "commercial", title: "Light Commercial HVAC", copy: "Reliable service for offices, shops, and small commercial spaces that need dependable comfort.", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85" },
  ],
  reviews: [
    { quote: "They explained the problem clearly, showed up when they said they would, and had the house comfortable again the same day.", name: "Sarah M.", location: "Local homeowner" },
    { quote: "No pressure and no mystery. The technician gave us clear options and the work was cleaner than I expected.", name: "James R.", location: "Local homeowner" },
    { quote: "Fast, professional, and easy to deal with. I finally have an HVAC company I would actually call again.", name: "Nicole T.", location: "Local homeowner" },
    { quote: "The technician was respectful of the house, answered every question, and fixed the issue without turning it into a sales pitch.", name: "Robert K.", location: "Local homeowner" },
    { quote: "Our AC quit on a hot afternoon. They got us scheduled quickly and had cold air back before dinner.", name: "Michael R.", location: "Local homeowner" },
    { quote: "The replacement process was straightforward from estimate to final walkthrough. Everything felt organized and professional.", name: "David M.", location: "Local homeowner" },
  ],
  projects: [
    {
      title: "Outdoor system upgrade",
      before: "https://images.unsplash.com/photo-1631545806609-94b8478bbd8b?auto=format&fit=crop&w=1400&q=85",
      after: "https://images.unsplash.com/photo-1626178793926-22b28830aa30?auto=format&fit=crop&w=1400&q=85",
    },
    {
      title: "Heating system replacement",
      before: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1400&q=85",
      after: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1400&q=85",
    },
  ],
  faqs: [
    { question: "How quickly can I get service?", answer: "Availability depends on the day and season, but the site is designed to make same-day and urgent scheduling easy to offer when the business supports it." },
    { question: "Should I repair or replace my HVAC system?", answer: "A technician should inspect the equipment first. Age, repair cost, efficiency, comfort problems, and expected remaining life all matter." },
    { question: "How often should HVAC maintenance be scheduled?", answer: "Many homeowners schedule cooling service before summer and heating service before winter so problems are found before peak season." },
    { question: "Do you service heat pumps?", answer: "Yes. The master service list can cover heat-pump diagnostics, repair, maintenance, and replacement when the business offers them." },
    { question: "Can I request service online?", answer: "Yes. Use the Schedule Service button or call directly. The final business version can connect the form to the company's actual booking workflow." },
    { question: "What areas do you serve?", answer: "The service-area section is intentionally configurable so each business can list its real cities, neighborhoods, and surrounding communities." },
  ],
  serviceAreas: ["Your main city", "North side", "South side", "East side", "West side", "Surrounding communities"],
} as const
