export const siteConfig = {
  brand: {
    name: "Prime Heating & Cooling",
    shortName: "PRIME HEATING & COOLING",
    tagline: "Heating · Cooling · Indoor Comfort",
    city: "Your Service Area",
    state: "",
    phoneDisplay: "(555) 555-0100",
    phoneHref: "+15555550100",
    email: "service@primehvac.com",
  },
  hero: {
    eyebrow: "4.9★ rated local HVAC team",
    heading: "Comfort back. Without the runaround.",
    body: "Fast HVAC help. Clear answers. Careful work.",
    image: "/hvac/prime-hero.jpg",
    imageAlt: "Smiling HVAC technician beside residential air conditioning equipment",
  },
  trust: [
    "Fast appointment options",
    "Licensed & insured",
    "Clear recommendations",
    "Quality workmanship",
  ],
  stats: [
    { value: "4.9★", label: "Homeowner rating" },
    { value: "Fast", label: "Appointment options" },
    { value: "Clear", label: "Options before work starts" },
    { value: "Local", label: "Neighborhood service" },
  ],
  services: [
    {
      key: "cooling",
      title: "AC Repair",
      copy: "No cold air, weak airflow, strange noises, or an AC that cannot keep up.",
      image: "/hvac/ac-repair.svg",
      imageAlt: "HVAC technician servicing a residential air conditioning system",
    },
    {
      key: "heating",
      title: "Heating & Furnace Repair",
      copy: "Find the problem, explain the options, and get dependable heat moving again.",
      image: "/hvac/furnace-repair.svg",
      imageAlt: "Technician inspecting and repairing a residential furnace",
    },
    {
      key: "air",
      title: "Indoor Air Quality",
      copy: "Cleaner air, better filtration, balanced humidity, and healthier indoor comfort.",
      image: "/hvac/air-quality.svg",
      imageAlt: "Indoor air quality control showing a healthy air reading",
    },
    {
      key: "duct",
      title: "Ductwork & Airflow",
      copy: "Help for weak airflow, uneven rooms, damaged ducts, and wasted comfort.",
      image: "/hvac/ductwork.svg",
      imageAlt: "HVAC technician inspecting ductwork and airflow",
    },
    {
      key: "thermostat",
      title: "Thermostats & Smart Controls",
      copy: "Setup, replacement, and control troubleshooting without the technical headache.",
      image: "/hvac/thermostat.svg",
      imageAlt: "Technician helping a homeowner with a smart thermostat",
    },
    {
      key: "maintenance",
      title: "Maintenance & Tune-Ups",
      copy: "Seasonal checks that catch small problems before they become expensive breakdowns.",
      image: "https://www.chiefhvacrepair.com/images/img-9f9d64afb5.webp",
      imageAlt: "HVAC technician inspecting an outdoor condenser during maintenance",
    },
    {
      key: "installation",
      title: "System Replacement",
      copy: "Clear replacement choices, clean installation, startup, testing, and final walkthrough.",
      image: "https://pub-532352f22580429d98f84286f6a24fd4.r2.dev/soflocooling/soflocooling-ac-install.png",
      imageAlt: "Two HVAC technicians installing a replacement outdoor condenser",
    },
    {
      key: "emergency",
      title: "Emergency HVAC Service",
      copy: "Urgent heating and cooling help when comfort cannot wait until tomorrow.",
      image: "https://newsroom.submitmypressrelease.com/system/posts/images/001/375/906/large/AC-Insurance-Coverage.jpeg",
      imageAlt: "HVAC technician ready for urgent residential service",
    },
    {
      key: "commercial",
      title: "Light Commercial HVAC",
      copy: "Dependable heating and cooling service for offices, shops, and small businesses.",
      image: "https://flowcrafthvac.com/assets/service-ac-action-U7V1tFbT.png",
      imageAlt: "Commercial rooftop HVAC technician servicing equipment",
    },
  ],
  reviews: [
    { quote: "They were on time, explained the problem in plain English, and had the AC running again before the house got miserable.", name: "Sarah M.", location: "Homeowner" },
    { quote: "I knew what the options were before any work started. No pressure, no confusing pitch.", name: "James R.", location: "Homeowner" },
    { quote: "Clean work, easy communication, and no surprises when the job was finished.", name: "Nicole T.", location: "Homeowner" },
    { quote: "The technician listened first, checked the system, then showed me exactly what was wrong.", name: "Robert K.", location: "Homeowner" },
    { quote: "Our AC quit in the afternoon. They found an opening quickly and got cold air moving again that day.", name: "Michael R.", location: "Homeowner" },
    { quote: "The replacement was organized from estimate through final walkthrough. Everything felt straightforward.", name: "David M.", location: "Homeowner" },
  ],
  projects: [
    {
      title: "Cooling system service",
      image: "https://i.pinimg.com/736x/15/2c/15/152c15588f52808e03a8bed1db8388cd.jpg",
      imageAlt: "Technicians diagnosing an outdoor residential air conditioning unit",
      copy: "Hands-on diagnosis where cooling problems start, followed by a clear explanation of the fix.",
    },
    {
      title: "Equipment inspection",
      image: "https://cdn.prod.website-files.com/66d218c3666112b4c63d51b3/674f36761720484094617838_ac-service-img%20copy.webp",
      imageAlt: "HVAC technician inspecting equipment during a service visit",
      copy: "A careful equipment check before repair, maintenance, or replacement decisions are made.",
    },
    {
      title: "Comfort controls",
      image: "https://le-cdn.hibuwebsites.com/e9facf8024b9407c8fa39a33dede1ab6/dms3rep/multi/opt/MicrosoftTeams-image%2B%2818%29-640w.png",
      imageAlt: "Technician showing a homeowner how to use a smart thermostat",
      copy: "Simple control setup so the system is easier to understand and more comfortable to live with.",
    },
  ],
  local: {
    image: "https://cdn.prod.website-files.com/650def70d00462f63fded491/652f78c18a78cacb706555d7_emergency-hvac-services.webp",
    imageAlt: "Smiling local HVAC technician beside an outdoor air conditioning unit",
    badges: [
      "Local technicians",
      "Fast response",
      "Residential HVAC",
      "Repair & replacement",
      "Nearby neighborhoods",
      "Call to confirm your area",
    ],
  },
  faqs: [
    { question: "How quickly can I get service?", answer: "Availability changes by day and season. Call or request service online and we can confirm the earliest opening." },
    { question: "Should I repair or replace my HVAC system?", answer: "That depends on equipment age, repair cost, comfort, efficiency, and expected remaining life. We can inspect the system and explain both options." },
    { question: "How often should HVAC maintenance be scheduled?", answer: "Many homeowners schedule cooling service before summer and heating service before winter so small problems are found before peak season." },
    { question: "Do you service heat pumps?", answer: "Yes. Heat-pump diagnostics, repair, maintenance, and replacement can be handled as part of residential HVAC service." },
    { question: "Can I request service online?", answer: "Yes. Use Schedule Service or call directly and tell us what is happening." },
    { question: "Do you service my neighborhood?", answer: "We serve homeowners throughout the local area and nearby communities. Call to confirm your address and the earliest available appointment." },
  ],
  serviceAreas: [
    "Your neighborhood",
    "Nearby communities",
    "Fast local response",
    "Residential service",
    "Local technicians",
    "Call to confirm your area",
  ],
} as const
